package com.example.solofit.model

class User {
    var userID: Int = 0            // Primary key (autogenerated by SQLite)
    var level: Int
    var currentExp: Int
    var levelCap: Int
    var strengthPts: Int
    var endurancePts: Int
    var vitalityPts: Int

    // Constructor without ID – used before inserting into DB
    constructor(
        level: Int,
        currentExp: Int,
        levelCap: Int,
        strengthPts: Int,
        endurancePts: Int,
        vitalityPts: Int
    ) {
        this.level = level
        this.currentExp = currentExp
        this.levelCap = levelCap
        this.strengthPts = strengthPts
        this.endurancePts = endurancePts
        this.vitalityPts = vitalityPts
    }

    // Constructor with ID – used when loading from DB
    constructor(
        userID: Int,
        level: Int,
        currentExp: Int,
        levelCap: Int,
        strengthPts: Int,
        endurancePts: Int,
        vitalityPts: Int
    ) {
        this.userID = userID
        this.level = level
        this.currentExp = currentExp
        this.levelCap = levelCap
        this.strengthPts = strengthPts
        this.endurancePts = endurancePts
        this.vitalityPts = vitalityPts
    }

    override fun toString(): String {
        return "User{" +
                "userID=$userID" +
                ", level=$level" +
                ", currentExp=$currentExp" +
                ", levelCap=$levelCap" +
                ", strengthPts=$strengthPts" +
                ", endurancePts=$endurancePts" +
                ", vitalityPts=$vitalityPts" +
                '}'
    }
}
