package com.example.solofit.model

class User {
    var userID: Int = 0            // Primary key (autogenerated by SQLite)
    var username: String
    var pfpUri: String?
    var userTitle: String
    var level: Int
    var currentExp: Float  // display, troy updated this to float
    var levelCap: Int
    var strengthPts: Int //display
    var endurancePts: Int //display
    var vitalityPts: Int //display

    // Constructor without ID – used before inserting into DB
    constructor(
        username: String,
        pfpUri: String?,
        userTitle: String,
        level: Int,
        currentExp: Float,
        levelCap: Int,
        strengthPts: Int,
        endurancePts: Int,
        vitalityPts: Int
    ) {
        this.username = username
        this.pfpUri = pfpUri
        this.userTitle = userTitle
        this.level = level
        this.currentExp = currentExp
        this.levelCap = levelCap
        this.strengthPts = strengthPts
        this.endurancePts = endurancePts
        this.vitalityPts = vitalityPts
    }

    // Constructor with ID – used when loading from DB
    constructor(
        userID: Int,
        username: String,
        pfpUri: String?,
        userTitle: String,
        level: Int,
        currentExp: Float,
        levelCap: Int,
        strengthPts: Int,
        endurancePts: Int,
        vitalityPts: Int
    ) {
        this.userID = userID
        this.username = username
        this.pfpUri = pfpUri
        this.userTitle = userTitle
        this.level = level
        this.currentExp = currentExp
        this.levelCap = levelCap
        this.strengthPts = strengthPts
        this.endurancePts = endurancePts
        this.vitalityPts = vitalityPts
    }

    override fun toString(): String {
        return "User{" +
                "userID=$userID" +
                ", username='$username'" +
                ", pfp=$pfpUri" +
                ", userTitle='$userTitle'" +
                ", level=$level" +
                ", currentExp=$currentExp" +
                ", levelCap=$levelCap" +
                ", strengthPts=$strengthPts" +
                ", endurancePts=$endurancePts" +
                ", vitalityPts=$vitalityPts" +
                '}'
    }
}
